In [2]:
#1. Business Problem
""" 
import numpy as np
import pandas as pd
print("Pandas version:",pd.__version__)
print("Numpy version:",np.__version__)

Pandas version: 2.3.3
Numpy version: 2.3.5

In [3]:
!pip install pyodbc

Requirement already satisfied: pyodbc in c:\users\ramesh\anaconda3\lib\site-packages (5.3.0)

In [4]:
import pyodbc
#Connection
c = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    r"SERVER=DESKTOP-8HDLIIL\SQLEXPRESS;"
    "DATABASE=master;"
    "Trusted_Connection=yes;"
)
print("Connected successfully!")

Connected successfully!

In [5]:
df = pd.read_excel("Online Retail.xlsx")
print("Loaded successfully")

Loaded successfully

In [18]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [10]:
df.shape

(541909, 8)

In [11]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [13]:
df.describe

<bound method NDFrame.describe of        InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

               InvoiceDate  UnitPrice  CustomerID         Country
0      2010-12-01 08:26:00       2.55     17850.0  United Kingdom
1      2010-12-01 08:26:00       3.39     17850.0  United Kingdom
2      2010-12-01 08:26:00       2.75     17850.0  United Kingdom
3      2010-12-01 08:26:00       3.39     17850.0  United Kingdom
4      2010-12-01 08:26:00       3.39     17850.0  United Kingdom
...                    ...        ...         ...             ...
541904 2011-12-09 12:50:00       0.85     12680.0          France
541905 2011-12-09 12:50:00       2.10     12680.0          France
541906 2011-12-09 12:50:00       4.15     12680.0          France
541907 2011-12-09 12:50:00       4.15     12680.0          France
541908 2011-12-09 12:50:00       4.95     12680.0          France

[541909 rows x 8 columns]>

In [6]:
df["Revenue"]=df["Quantity"]*df["UnitPrice"]

In [18]:
df[["Quantity","UnitPrice","Revenue"]].head()

   Quantity  UnitPrice  Revenue
0         6       2.55    15.30
1         6       3.39    20.34
2         8       2.75    22.00
3         6       3.39    20.34
4         6       3.39    20.34

In [13]:
#Highest Revenue Country
result=df.groupby("Country")["Revenue"].sum() 
result.sort_values(ascending=False).head(1)

Country
United Kingdom    8187806.364
Name: Revenue, dtype: float64

In [14]:
#Which products generate the most revenue?
result=df.groupby("StockCode")["Revenue"].sum()
result.sort_values(ascending=False).head()

StockCode
DOT       206245.48
22423     164762.19
47566      98302.98
85123A     97894.50
85099B     92356.03
Name: Revenue, dtype: float64

In [15]:
#Which products are sold in the largest quantities?
result=df.groupby("StockCode")["Quantity"].sum()
result.sort_values(ascending=False).head()

StockCode
22197     56450
84077     53847
85099B    47363
85123A    38830
84879     36221
Name: Quantity, dtype: int64

In [16]:
#Which country sells the most products?
result=df.groupby("Country")["Quantity"].sum()
result.sort_values(ascending=False).head(1)

Country
United Kingdom    4263829
Name: Quantity, dtype: int64

In [21]:
#Which customers generate the most revenue?
result=df.groupby("CustomerID")["Revenue"].sum()
result.sort_values(ascending=False).head()

CustomerID
14646.0    279489.02
18102.0    256438.49
17450.0    187482.17
14911.0    132572.62
12415.0    123725.45
Name: Revenue, dtype: float64

In [25]:
#Which country has the highest average order value?
result=df.groupby("Country")["Revenue"].sum()/df.groupby("Country")["InvoiceNo"].nunique()
result.sort_values(ascending=False).head(1)

Country
Netherlands    2818.431089
dtype: float64

In [28]:
#Which customer has placed the highest number of orders?
result=df.groupby("CustomerID")["InvoiceNo"].nunique()
result.sort_values(ascending=False).head(1)

CustomerID
14911.0    248
Name: InvoiceNo, dtype: int64

In [37]:
#Which customer generated the highest total revenue AND how many orders did they place?
result=df.groupby("CustomerID").agg(
    Total_Sales=("Revenue","sum"),
    No_Of_Orders=("InvoiceNo","nunique")
)
result.sort_values("Total_Sales",ascending=False).head(1)

            Total_Sales  No_Of_Orders
CustomerID
14646.0       279489.02            77